name: cctp-dst
description: Indexing circle etheruem cctp contracts
startBlock: 4131742
userId: google-oauth2%7C113106604109449522744
projectId: 9b8821f7-0942-4afa-b739-6d2560166cb2
network: Base
user: prady-cctp
schema:
  file: ./studio.schema.ts
execution: parallel
Resources:
  - Name: messageTransmitter
    Abi: src/abis/messageTransmitter.json
    Type: contract/event
    Address: "0xAD09780d193884d503182aD4588450C416D6F9D4"
    Triggers:
      - Event: MessageReceived(address indexed,uint32,uint64 indexed,bytes32,bytes)
        Handler: src/handlers/MessageReceived.MessageReceivedHandler
