name: cctp-dst
description: Indexing circle etheruem cctp contracts
startBlock: 49369579
userId: google-oauth2%7C113106604109449522744
projectId: 9b8821f7-0942-4afa-b739-6d2560166cb2
network: Polygon
user: prady-cctp
schema:
  file: ./studio.schema.ts
execution: parallel
Resources:
  - Name: messageTransmitter
    Abi: src/abis/messageTransmitter.json
    Type: contract/event
    Address: "0xF3be9355363857F3e001be68856A2f96b4C39Ba9"
    Triggers:
      - Event: MessageReceived(address indexed,uint32,uint64 indexed,bytes32,bytes)
        Handler: src/handlers/MessageReceived.MessageReceivedHandler
