name: cctp-src
description: Indexing circle etheruem cctp contracts
startBlock: 16730025
userId: google-oauth2%7C113106604109449522744
projectId: 9b8821f7-0942-4afa-b739-6d2560166cb2
network: Ethereum
user: prady-cctp
schema:
  file: ./studio.schema.ts
execution: parallel
Resources:
  - Name: tokenmessenger
    Abi: src/abis/tokenmessenger.json
    Type: contract/event
    Address: "0xBd3fa81B58Ba92a82136038B25aDec7066af3155"
    Triggers:
      - Event: DepositForBurn(uint64 indexed,address indexed,uint256,address indexed,bytes32,uint32,bytes32,bytes32)
        Handler: src/handlers/DepositForBurn.DepositForBurnHandler
  - Name: tokenMinter
    Abi: src/abis/tokenMinter.json
    Type: contract/event
    Address: "0xc4922d64a24675E16e1586e3e3Aa56C06fABe907"
    Triggers:
      - Event: SetBurnLimitPerMessage(address indexed,uint256)
        Handler: src/handlers/SetBurnLimitPerMessage.SetBurnLimitPerMessageHandler
